# Transperfect scripts for Language translation
name: Automated Language Translation Transperfect - Upload

on:
    schedule:
        - cron: '0 * * * *'  # Run every hour (at minute 0)
    workflow_dispatch:

jobs:
    

    job_application:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 1

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install undetected-chromedriver pyautogui setuptools openai flask-cors flask

            - name: Setup Chrome
              uses: browser-actions/setup-chrome@v1
              with:
                chrome-version: stable

            - name: Run LinkedIn Auto Job Applier
              run: |
                  python runAiBot.py
              env:
                  LN_USERNAME: ${{ secrets.LN_USERNAME }}
                  LN_PASSWORD: ${{ secrets.LN_PASSWORD }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

