name: LinkedIn Auto Job Applier

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  # Allows manual triggering from GitHub Actions tab
  workflow_dispatch:

jobs:
  job_application:
    # Change from ubuntu-latest to self-hosted runner
    runs-on: self-hosted 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # We can skip Python setup if already installed on your self-hosted runner
      - name: Set up Python
        run: |
          # Check if Python is already installed
          python3 --version || echo "Python needs to be installed manually"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install undetected-chromedriver pyautogui setuptools google-generativeai openai flask-cors flask

      # No need for special Chrome setup on your machine if Chrome is already installed
      # No need for xvfb on macOS as it has native GUI

      - name: Prepare config files
        run: |
          # Update configuration files as needed
          sed -i '' "s/gemini_api_key = \"YOUR_GEMINI_API_KEY\"/gemini_api_key = os.environ.get(\"GEMINI_API_KEY\", \"\")/g" config/secrets.py
          # Only disable pause options if running in fully automated mode
          # sed -i '' "s/pause_at_failed_question = True/pause_at_failed_question = False/g" config/settings.py
          # sed -i '' "s/pause_before_submit = True/pause_before_submit = False/g" config/settings.py

      - name: Run LinkedIn Auto Job Applier
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          LN_USERNAME: ${{ secrets.LN_USERNAME }}
          LN_PASSWORD: ${{ secrets.LN_PASSWORD }}
        run: |
          # Replace hardcoded credentials with environment variables if they exist
          if [ ! -z "$LN_USERNAME" ]; then
            sed -i '' "s/username = \".*\"/username = \"$LN_USERNAME\"/g" config/secrets.py
          fi
          
          if [ ! -z "$LN_PASSWORD" ]; then
            sed -i '' "s/password = \".*\"/password = \"$LN_PASSWORD\"/g" config/secrets.py
          fi
          
          # Run the application
          python3 runAiBot.py

