name: LinkedIn Auto Job Applier

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  # Allows manual triggering from GitHub Actions tab
  workflow_dispatch:

jobs:
  apply-to-jobs:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install Chrome and dependencies
        run: |
          # Install required packages
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb

          # Get latest Chrome and ChromeDriver versions
          CHROME_VERSION=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE)
          echo "Latest Chrome version: $CHROME_VERSION"
          
          # Download and install Chrome for Testing
          wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_VERSION/linux64/chrome-linux64.zip"
          unzip -q chrome-linux64.zip
          sudo mv chrome-linux64/chrome /usr/bin/google-chrome
          sudo chmod +x /usr/bin/google-chrome
          
          # Download and install matching ChromeDriver
          wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_VERSION/linux64/chromedriver-linux64.zip"
          unzip -q chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
          # Set up directories and permissions
          sudo mkdir -p /home/runner/Downloads
          sudo chmod 777 /home/runner/Downloads
          mkdir -p logs/screenshots
          chmod -R 777 logs
          
          # Set up virtual display
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          sleep 3
          
          # Print versions for debugging
          echo "Chrome version:"
          google-chrome --version || true
          echo "ChromeDriver version:"
          chromedriver --version || true
          echo "Display: $DISPLAY"
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          
      - name: Configure for headless mode
        run: |
          # Update settings.py for headless mode
          cat << EOF >> config/settings.py
          
          # Headless mode configuration for GitHub Actions
          import os
          running_in_actions = True
          run_in_background = True
          safe_mode = True
          disable_extensions = True
          smooth_scroll = False
          keep_screen_awake = False
          stealth_mode = False
          showAiErrorAlerts = False
          downloads_path = "/home/runner/Downloads"  # Set downloads path for GitHub Actions
          EOF
          
      - name: Update credentials
        run: |
          python -c "
          import os
          
          # Read current content
          with open('config/secrets.py', 'r') as f:
              content = f.read()
          
          # Update the content
          if 'username = os.environ.get(\"LN_USERNAME\"' not in content:
              with open('config/secrets.py', 'a') as f:
                  f.write('\n# Auto-inserted by GitHub Actions\n')
                  f.write('username = os.environ.get(\"LN_USERNAME\", \"\")\n')
                  f.write('password = os.environ.get(\"LN_PASSWORD\", \"\")\n')
          "
          
      - name: Run LinkedIn Auto Job Applier
        env:
          DISPLAY: ":99.0"
          GITHUB_ACTIONS: "true"
          CI: "true"
          PYTHONPATH: "${PYTHONPATH}:/home/runner/work/LinkedJobApply/LinkedJobApply"
          DOWNLOADS_PATH: "/home/runner/Downloads"
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          LN_USERNAME: ${{ secrets.LN_USERNAME }}
          LN_PASSWORD: ${{ secrets.LN_PASSWORD }}
        run: |
          # Print debugging info
          echo "Python path: $PYTHONPATH"
          echo "Downloads path: $DOWNLOADS_PATH"
          echo "Chrome version:"
          google-chrome --version
          echo "ChromeDriver version:"
          chromedriver --version
          python runAiBot.py

