name: LinkedIn Auto Job Applier

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  # Allows manual triggering from GitHub Actions tab
  workflow_dispatch:

jobs:
  apply-to-jobs:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install Chrome and dependencies
        run: |
          # Install required packages
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb

          # Install Chrome using the new apt key method
          sudo mkdir -p /etc/apt/keyrings
          wget -q -O- https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /etc/apt/keyrings/google-chrome.gpg
          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          # Print Chrome version and get major version
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | awk -F'.' '{print $1}')
          echo "Chrome version: $CHROME_VERSION (Major: $CHROME_MAJOR_VERSION)"
          
          # Try to get matching chromedriver version, fall back through versions if needed
          CHROMEDRIVER_VERSION=""
          for VERSION in $CHROME_MAJOR_VERSION $(seq $((CHROME_MAJOR_VERSION-1)) $((CHROME_MAJOR_VERSION-5)) -1); do
            echo "Trying chromedriver version $VERSION..."
            RELEASE_URL="https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$VERSION"
            RESPONSE=$(curl -s "$RELEASE_URL")
            if [[ ! $RESPONSE =~ "Error" ]]; then
              CHROMEDRIVER_VERSION=$RESPONSE
              echo "Found compatible chromedriver version: $CHROMEDRIVER_VERSION"
              break
            fi
          done

          # If still no version found, try the latest release
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "Falling back to latest chromedriver version"
            CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          fi
          
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "Failed to find a compatible chromedriver version"
            exit 1
          fi
          
          echo "Installing chromedriver version: $CHROMEDRIVER_VERSION"
          
          # Download and install chromedriver
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip -q chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          
          # Set up directories and permissions
          sudo mkdir -p /home/runner/Downloads
          sudo chmod 777 /home/runner/Downloads
          mkdir -p logs/screenshots
          chmod -R 777 logs
          
          # Set up virtual display with delay
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          sleep 3  # Give Xvfb more time to start
          
          # Print versions and setup info
          echo "Chrome version:"
          google-chrome --version || true
          echo "Chromedriver version:"
          chromedriver --version || true
          echo "Display: $DISPLAY"
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          
      - name: Configure for headless mode
        run: |
          # Update settings.py for headless mode
          cat << EOF >> config/settings.py
          
          # Headless mode configuration for GitHub Actions
          import os
          running_in_actions = True
          run_in_background = True
          safe_mode = True
          disable_extensions = True
          smooth_scroll = False
          keep_screen_awake = False
          stealth_mode = False
          showAiErrorAlerts = False
          downloads_path = "/home/runner/Downloads"  # Set downloads path for GitHub Actions
          EOF
          
      - name: Update credentials
        run: |
          python -c "
          import os
          
          # Read current content
          with open('config/secrets.py', 'r') as f:
              content = f.read()
          
          # Update the content
          if 'username = os.environ.get(\"LN_USERNAME\"' not in content:
              with open('config/secrets.py', 'a') as f:
                  f.write('\n# Auto-inserted by GitHub Actions\n')
                  f.write('username = os.environ.get(\"LN_USERNAME\", \"\")\n')
                  f.write('password = os.environ.get(\"LN_PASSWORD\", \"\")\n')
          "
          
      - name: Run LinkedIn Auto Job Applier
        env:
          DISPLAY: ":99.0"
          GITHUB_ACTIONS: "true"
          CI: "true"
          PYTHONPATH: "${PYTHONPATH}:/home/runner/work/LinkedJobApply/LinkedJobApply"
          DOWNLOADS_PATH: "/home/runner/Downloads"
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          LN_USERNAME: ${{ secrets.LN_USERNAME }}
          LN_PASSWORD: ${{ secrets.LN_PASSWORD }}
        run: |
          # Print debugging info
          echo "Python path: $PYTHONPATH"
          echo "Downloads path: $DOWNLOADS_PATH"
          echo "Chrome version:"
          google-chrome --version
          echo "Chromedriver version:"
          chromedriver --version
          python runAiBot.py

