name: LinkedIn Auto Job Applier

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  # Allows manual triggering
  workflow_dispatch:

jobs:
  verify-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.LN_USERNAME }}" ] || [ -z "${{ secrets.LN_PASSWORD }}" ]; then
            echo "Error: Required secrets LN_USERNAME and/or LN_PASSWORD are not set"
            exit 1
          fi
          echo "Required secrets are properly configured"

  apply-to-jobs:
    needs: verify-secrets
    runs-on: ubuntu-latest
    
    env:
      GITHUB_ACTIONS: "true"
      CI: "true"
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      # ... existing Chrome and Python setup steps ...

      - name: Set up environment variables
        run: |
          echo "Setting up environment variables..."
          echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV
          echo "CI=true" >> $GITHUB_ENV
          echo "DISPLAY=:99.0" >> $GITHUB_ENV
          echo "LN_USERNAME=${{ secrets.LN_USERNAME }}" >> $GITHUB_ENV
          echo "LN_PASSWORD=${{ secrets.LN_PASSWORD }}" >> $GITHUB_ENV
          
          # Verify environment variables are set
          if [ -z "${LN_USERNAME}" ]; then
            echo "Error: LN_USERNAME is not set"
            exit 1
          fi
          if [ -z "${LN_PASSWORD}" ]; then
            echo "Error: LN_PASSWORD is not set"
            exit 1
          fi
          
          echo "Environment variables configured successfully"

      - name: Run LinkedIn Auto Job Applier
        env:
          DISPLAY: ":99.0"
          GITHUB_ACTIONS: "true"
          CI: "true"
          PYTHONPATH: "${PYTHONPATH}:/home/runner/work/LinkedJobApply/LinkedJobApply"
          DOWNLOADS_PATH: "/home/runner/Downloads"
          LN_USERNAME: ${{ secrets.LN_USERNAME }}
          LN_PASSWORD: ${{ secrets.LN_PASSWORD }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Print environment info (without exposing secrets)
          echo "Environment configuration:"
          echo "Python path: $PYTHONPATH"
          echo "Downloads path: $DOWNLOADS_PATH"
          echo "Display: $DISPLAY"
          echo "GITHUB_ACTIONS: $GITHUB_ACTIONS"
          echo "CI: $CI"
          echo "LN_USERNAME is set: ${{ secrets.LN_USERNAME != '' }}"
          echo "LN_PASSWORD is set: ${{ secrets.LN_PASSWORD != '' }}"
          
          # Run the bot
          python runAiBot.py